server:
  port: 8010

  spring:
  application:
    name: passengers
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/passengers?currentSchema=passengers_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka

